import Link from "next/link";
import { ArrowRight, Building2, Check, Globe, ImageIcon, KeyRound, MessageSquare, Palette, Users, Search, Heart, BellRing, Bot, Wrench, TrendingUp, FileText, Wallet, UserCog, LayoutTemplate, Share2, Send, ShieldCheck, Clock, Rocket, Download } from "lucide-react";
import { WhatsAppIcon } from "@/components/catalog/social-icons";
import { UrbiPublicFooter } from "./urbi-public-footer";
import { UrbiPublicNav } from "./urbi-public-nav";
import { HeroTilt } from "./hero-tilt";
import { UrbiFaqList } from "./urbi-faq-list";
import { UrbiReveal } from "./urbi-reveal";
import { UrbiPlans, type PublicPlan } from "./urbi-plans";
import { ContactCtaButton } from "./contact-cta-button";
import { SetupServiceSection } from "./setup-service-section";
import { FAQ_CATEGORIES } from "@/lib/faq-content";

const publicFeatures = [
 {icon:Search,color:"#1e658c",title:"Buscador y mapa",text:"Filtros por operación, tipo, zona, ambientes y más — vos elegís cuáles mostrar y cómo se llaman. Con vista de mapa para recorrer la zona."},
 {icon:WhatsAppIcon,color:"#22c55e",title:"Consultá por WhatsApp",text:"Cada ficha tiene un botón directo a WhatsApp con el mensaje ya armado, además del formulario de consulta clásico."},
 {icon:ImageIcon,color:"#12a7cd",title:"Fichas completas",text:"Fotos, plano, video, precio y todas las características. El visitante ve todo lo que necesita para decidir escribirte."},
 {icon:Heart,color:"#e0567a",title:"Favoritos",text:"Cualquier visitante puede guardar propiedades para comparar después, tenga cuenta o no."},
 {icon:BellRing,color:"#d97706",title:"Alertas de búsqueda",text:"Un interesado deja lo que busca y vos lo tenés guardado en tu panel, listo para cruzarlo contra tu cartera."},
 {icon:Building2,color:"#1e658c",title:"Emprendimientos",text:"Página propia para cada proyecto: etapa de obra, avance, financiación, amenities y formulario de consulta a medida."},
 {icon:Wrench,color:"#0f9d78",title:"Servicios adicionales",text:"Un catálogo aparte para tasaciones, seguros u otros servicios que ofrezcas, con su propio formulario de consulta."},
 {icon:Bot,color:"#7c5cff",title:"Asistente con IA",text:"Un chat en tu sitio que responde con tu cartera real — nunca inventa un precio ni una ubicación — y te deja la consulta cargada."},
 {icon:KeyRound,color:"#133453",title:"Portal del inquilino",text:"Tu inquilino entra con su email y DNI y ve su contrato, cada cuota con su estado y los documentos que le compartas."},
];

const adminGroups = [
 {title:"Tu cartera",icon:Building2,color:"#1e658c",items:[
  ["Propiedades","Alta, fotos, precios, destacadas y disponibilidad — todo desde un mismo lugar."],
  ["Emprendimientos","Cargá el proyecto y vinculale las unidades que lo componen."],
  ["Categorías propias","Tipos de propiedad, ciudades y barrios a tu medida."],
 ]},
 {title:"Tus contactos",icon:Users,color:"#e0567a",items:[
  ["Clientes y CRM","Una agenda para propietarios, interesados, inquilinos y garantes."],
  ["Consultas","Bandeja única de todas las consultas, asignable por agente."],
  ["Búsquedas guardadas","Las alertas de cada visitante, listas para cruzar con tu cartera."],
  ["Agenda de visitas","Propiedad, interesado y agente, con control de cruces de horario."],
 ]},
 {title:"Tu negocio",icon:Wallet,color:"#d97706",items:[
  ["Operaciones","Negociación, reserva, cierre — actualiza la disponibilidad sola."],
  ["Tasaciones","Seguimiento de cada pedido de tasación hasta el informe final."],
  ["Contratos","Partes, plazo, alquiler, depósito y garantía en un solo registro."],
  ["Cobranzas automáticas","Genera la cuota de cada mes, aplica mora y te avisa antes del vencimiento."],
 ]},
];

const customization = [
 {icon:LayoutTemplate,color:"#7c5cff",title:"3 plantillas de sitio","text":"Clásico, moderno o minimal — cambiá el diseño completo del sitio con un clic."},
 {icon:Palette,color:"#e0567a",title:"Tu marca, tus colores",text:"Logo de header y de footer por separado, favicon y 5 colores propios en todo el sitio."},
 {icon:Globe,color:"#12a7cd",title:"Dominio propio",text:"Usá tu subdominio gratis o conectá tu dominio. ¿No tenés uno? Te lo compramos y configuramos nosotros."},
 {icon:TrendingUp,color:"#0f9d78",title:"SEO y redes",text:"Título, descripción e imagen para cuando compartís tu sitio, con tu dominio verificado."},
 {icon:MessageSquare,color:"#d97706",title:"Popup de bienvenida",text:"Un anuncio editable a la entrada del sitio, con la frecuencia que prefieras."},
 {icon:Share2,color:"#1e658c",title:"Tus redes sociales",text:"WhatsApp, Instagram, Facebook y YouTube conectados en el header, footer y contacto."},
];

const differentiators = [
 {icon:Send,color:"#12a7cd",title:"Telegram al instante",text:"Un mensaje a tu Telegram apenas entra una consulta nueva."},
 {icon:Download,color:"#1e658c",title:"Se instala como app",text:"Tu sitio y tu panel se agregan a la pantalla de inicio, sin tiendas de aplicaciones."},
 {icon:ShieldCheck,color:"#0f9d78",title:"IA que no inventa datos",text:"El asistente solo responde con propiedades reales de tu cartera, nunca precios ni datos inventados."},
 {icon:UserCog,color:"#7c5cff",title:"Permisos por agente",text:"Elegís sección por sección qué puede ver y tocar cada persona de tu equipo."},
 {icon:FileText,color:"#e0567a",title:"Ajustes de alquiler sin sorpresas",text:"IPC, ICL o el índice que uses: la actualización queda como sugerencia hasta que vos la apruebes."},
];

const ctaPop = "inline-flex items-center gap-2 rounded-xl bg-[#208ab1] px-6 text-sm font-bold text-white shadow-[0_10px_30px_-6px_rgba(32,138,177,.5)] transition hover:bg-[#1e658c] hover:-translate-y-0.5";

export function UrbiLanding({plans,resellerSettings,resellerTiers,setupService}:{plans:PublicPlan[];resellerSettings:{activationBonusAmount:number;activationBonusDays:number};resellerTiers:{minActiveStores:number;percent:number}[];setupService:{enabled:boolean;price:number;steps:string[]}}) {
 const maxCommission=Math.max(0,...resellerTiers.map(t=>t.percent));
 const faqs=FAQ_CATEGORIES.flatMap(c=>c.questions).filter((_,i)=>[0,1,2,3,4,12].includes(i));
 return <main className="urbi-marketing min-h-screen bg-[#f7fafc] text-[#133453]">
  <UrbiPublicNav/>
  <section className="bg-[#133453] text-white">
   <div className="mx-auto grid max-w-7xl items-center gap-8 px-6 py-10 lg:grid-cols-[1fr_1.05fr] lg:gap-12 lg:py-14">
    <div><p className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-3 py-1.5 text-[11px] font-bold uppercase tracking-[.14em] text-[#51c2ec]"><Bot className="size-3.5 text-[#51c2ec]"/>CRM inmobiliario con inteligencia artificial</p>
    <h1 className="mt-5 text-4xl font-semibold leading-[1.1] tracking-[-.045em] sm:text-5xl lg:text-[52px]">Gestioná tu inmobiliaria.<br/><span className="text-[#51c2ec]">La IA te ayuda a vender.</span></h1>
    <p className="mt-4 max-w-lg text-base leading-relaxed text-[#bad0df]">Propiedades, contactos, consultas, visitas, contratos y cobranzas en un solo CRM. Además, tenés tu sitio web y un agente de IA que atiende interesados las 24 horas.</p>
    <div className="mt-6 flex flex-wrap gap-3"><Link href="#precios" className={`h-12 ${ctaPop}`}>Ver planes <ArrowRight className="size-4"/></Link><Link href="/demo" className="inline-flex h-12 items-center gap-2 rounded-xl border border-white/15 bg-white px-6 text-sm font-semibold text-[#133453] hover:bg-[#edf5f9]">Probar el CRM</Link></div>
    <div className="mt-6 flex flex-wrap gap-x-5 gap-y-2 text-xs text-[#bad0df]">{["CRM inmobiliario","Sitio web incluido","Agente IA 24/7"].map(t=><span key={t} className="flex items-center gap-1.5"><Check className="size-3.5 text-[#51c2ec]"/>{t}</span>)}</div>
    <p className="mt-5 text-sm text-[#bad0df]">¿No sabés cómo armarla? <Link href="#armamos-por-vos" className="font-bold text-[#51c2ec] hover:text-[#51c2ec]">La armamos nosotros →</Link></p>
    </div>
    <HeroTilt/>
   </div>
  </section>
  <section className="border-b border-[#e2ecf2] bg-white"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-6 px-6 py-7"><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#8294a3]">Todo conectado en una sola plataforma</p><div className="flex flex-wrap gap-7 text-sm font-medium">{[[Users,"#1e658c","Contactos y consultas"],[Building2,"#0f9d78","Propiedades y visitas"],[Wallet,"#d97706","Contratos y cobranzas"],[Bot,"#7c5cff","Agente de ventas IA"]].map(([Icon,color,t])=>{const I=Icon as typeof Building2;return <span key={String(t)} className="flex items-center gap-2"><I className="size-4" style={{color:color as string}}/>{String(t)}</span>;})}</div></div></section>
  <section id="funcionalidades" className="mx-auto max-w-7xl scroll-mt-24 px-6 py-20 lg:py-24"><div className="grid gap-5 md:grid-cols-2 md:items-end"><div><p className="urbi-eyebrow">Tu vidriera digital, incluida en el CRM</p><h2 className="mt-3 max-w-lg text-3xl font-semibold leading-tight tracking-tight sm:text-4xl">Un sitio web que convierte visitas en oportunidades.</h2></div><p className="max-w-md text-base leading-relaxed text-[#61758a] md:ml-auto">Mostrá tu cartera con tu marca, recibí consultas y hacé que cada interesado llegue directamente a tu CRM.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{publicFeatures.map(({icon:Icon,color,title,text},i)=><UrbiReveal key={title} direction="up" delay={(i%3)*90} pop><article className="rounded-2xl border border-[#e0eaf1] bg-white p-7"><div className="flex size-11 items-center justify-center rounded-xl" style={{backgroundColor:color}}><Icon className="size-5 text-white"/></div><h3 className="mt-6 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-[#61758a]">{text}</p></article></UrbiReveal>)}</div><div className="mt-12 text-center"><Link href="/registro" className={`h-12 ${ctaPop}`}>Quiero mi CRM y mi web <ArrowRight className="size-4"/></Link></div></section>
  <section id="como-funciona" className="bg-[#133453] text-white"><div className="mx-auto max-w-7xl px-6 py-20"><div className="grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#51c2ec]">Así de simple</p><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">De tu inmobiliaria a tu página online, en 5 minutos.</h2><p className="mt-5 text-base leading-relaxed text-[#bad0df]">Elegí un plan, dale tu identidad al sitio y empezá a mostrar tus propiedades. Urbi se ocupa de la plataforma; vos mantenés tu página al día.</p><Link href="/registro" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#51c2ec] hover:text-[#51c2ec]">Ver los planes <ArrowRight className="size-4"/></Link></div><div className="space-y-0">{[["01","Elegí tu plan","Consultá los precios y las condiciones, y creá tu cuenta — sin instalar nada."],["02","Dale tu identidad","Sumá el logo, los colores y la plantilla de tu inmobiliaria."],["03","Cargá tus propiedades","Fotos, precios y características desde tu panel."],["04","Compartí tu nueva web","Poné el enlace en tus redes y recibí consultas sobre tus avisos."]].map(([n,t,d])=><div key={n} className="flex gap-5 border-b border-white/10 py-5 first:pt-0 last:border-0"><span className="pt-1 font-mono text-xs text-[#51c2ec]">{n}</span><div><h3 className="text-lg font-medium">{t}</h3><p className="mt-1 text-sm leading-relaxed text-[#bad0df]">{d}</p></div></div>)}</div></div><div className="mt-12 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-[#51c2ec]/40 bg-[#51c2ec]/15 p-6"><p className="max-w-lg text-sm leading-relaxed text-[#bad0df]"><Rocket className="mb-1 inline size-4 text-[#51c2ec]"/> <strong className="text-white">¿Preferís que lo hagamos nosotros?</strong> Te configuramos la identidad del sitio y cargamos tus primeras propiedades por un pago único.</p><Link href="#armamos-por-vos" className={`shrink-0 h-11 ${ctaPop}`}>Quiero que me la armen <ArrowRight className="size-4"/></Link></div></div></section>
  <section id="clientes" className="mx-auto max-w-7xl scroll-mt-24 px-6 py-20"><p className="urbi-eyebrow">CRM creado para inmobiliarias</p><h2 className="mt-3 max-w-2xl text-3xl font-semibold tracking-tight">De la primera consulta al contrato, todo queda conectado.</h2><p className="mt-4 max-w-2xl text-base leading-relaxed text-[#61758a]">Centralizá tu cartera, el seguimiento comercial y la administración diaria sin adaptar un CRM genérico a tu negocio.</p><div className="mt-10 grid gap-8 md:grid-cols-3">{adminGroups.map(({title,icon:Icon,color,items})=><div key={title} className="rounded-2xl border border-[#e0eaf1] bg-white p-7"><div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-lg" style={{backgroundColor:color}}><Icon className="size-4.5 text-white"/></span><h3 className="text-lg font-semibold">{title}</h3></div><ul className="mt-5 flex flex-col gap-4">{items.map(([t,d])=><li key={t} className="border-t border-[#edf3f7] pt-4 first:border-0 first:pt-0"><p className="text-sm font-semibold">{t}</p><p className="mt-1 text-sm leading-relaxed text-[#61758a]">{d}</p></li>)}</ul></div>)}</div><div className="mt-12 text-center"><Link href="/registro" className={`h-12 ${ctaPop}`}>Quiero ordenar mi inmobiliaria <ArrowRight className="size-4"/></Link></div></section>
  <section id="ia" className="scroll-mt-24 bg-[#171b3c] text-white"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-20 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#a998ff]">Agente de ventas con IA</p><h2 className="mt-4 max-w-xl text-3xl font-semibold tracking-tight sm:text-4xl">Tu inmobiliaria responde incluso cuando tu equipo no está conectado.</h2><p className="mt-5 max-w-xl text-base leading-relaxed text-white/70">La IA conversa con cada interesado usando la información real de tu cartera, recomienda propiedades y transforma la charla en una oportunidad dentro del CRM.</p><Link href="#precios" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-[#7c5cff] px-6 py-3 text-sm font-bold text-white transition hover:-translate-y-0.5 hover:bg-[#6b4fe0]">Ver planes con IA <ArrowRight className="size-4"/></Link></div><div className="grid gap-4 sm:grid-cols-2">{[[Search,"Busca en tu cartera","Filtra propiedades publicadas por zona, tipo, operación, ambientes y presupuesto."],[ShieldCheck,"Responde sin inventar","Respeta precios, ubicaciones y disponibilidad reales cargados en el CRM."],[MessageSquare,"Captura cada consulta","Pide los datos del interesado y crea automáticamente la oportunidad comercial."],[Clock,"Agenda visitas 24/7","Puede coordinar una visita desde la conversación, incluso fuera de horario."]].map(([Icon,title,text])=>{const I=Icon as typeof Bot;return <article key={String(title)} className="rounded-2xl border border-white/10 bg-white/5 p-6"><I className="size-6 text-[#a998ff]"/><h3 className="mt-4 font-semibold">{String(title)}</h3><p className="mt-2 text-sm leading-relaxed text-white/65">{String(text)}</p></article>;})}</div></div></section>
  <section id="personalizacion" className="scroll-mt-24 border-y border-[#e2ecf2] bg-white py-20"><div className="mx-auto max-w-7xl px-6"><p className="urbi-eyebrow">Es tu inmobiliaria, se tiene que ver como tal</p><h2 className="mt-3 max-w-2xl text-3xl font-semibold tracking-tight">Un sitio con tu identidad, no una plantilla genérica.</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{customization.map(({icon:Icon,color,title,text},i)=><UrbiReveal key={title} direction="up" delay={(i%3)*90} pop><article className="rounded-2xl border border-[#e0eaf1] bg-[#f7fafc] p-7"><div className="flex size-11 items-center justify-center rounded-xl" style={{backgroundColor:color}}><Icon className="size-5 text-white"/></div><h3 className="mt-6 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-[#61758a]">{text}</p></article></UrbiReveal>)}</div><div className="mt-12 text-center"><Link href="#armamos-por-vos" className="inline-flex items-center gap-2 text-sm font-bold text-[#1e658c] hover:text-[#133453]">¿No sabés cuál elegir? Te ayudamos a definirla <ArrowRight className="size-4"/></Link></div></div></section>
  <section className="bg-[#51c2ec]"><div className="mx-auto max-w-7xl px-6 py-20"><p className="text-xs font-bold uppercase tracking-[.16em] text-white">Lo que nos hace distintos</p><h2 className="mt-3 max-w-2xl text-3xl font-semibold tracking-tight text-white">Detalles pensados para tu operación diaria.</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{differentiators.map(({icon:Icon,title,text})=><article key={title} className="flex gap-4 rounded-2xl bg-white p-6"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-[#133453]"><Icon className="size-4.5 text-white"/></span><div><h3 className="font-semibold">{title}</h3><p className="mt-1.5 text-sm leading-relaxed text-[#61758a]">{text}</p></div></article>)}</div></div></section>
  <section id="precios" className="scroll-mt-20 border-y border-[#e2ecf2] bg-[#edf4f8] py-20"><div className="mx-auto max-w-6xl px-6"><div className="mx-auto mb-10 max-w-2xl text-center"><p className="urbi-eyebrow">Planes para cada etapa</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Elegí cuánto querés potenciar tu inmobiliaria.</h2><p className="mt-4 text-sm leading-relaxed text-[#61758a]">Compará límites y herramientas: desde la presencia digital y el CRM hasta el agente de ventas con IA. Podés empezar con el plan que hoy necesitás.</p></div><UrbiPlans plans={plans}/><p className="mt-6 text-center text-xs text-[#61758a]">Todos los planes incluyen acceso a la plataforma y al sitio inmobiliario. Cada tarjeta indica sus límites y funciones disponibles.</p></div></section>
  {setupService.enabled&&<SetupServiceSection price={setupService.price} steps={setupService.steps}/>}
  <section id="socios" className="scroll-mt-24 bg-[#51c2ec]"><div className="mx-auto max-w-7xl px-6 py-20"><div className="grid gap-8 rounded-3xl bg-white p-8 sm:p-12 md:grid-cols-[1fr_auto] md:items-center"><div><p className="urbi-eyebrow">Revendedores · Socios comerciales</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">Recomendá páginas inmobiliarias. Generá ingresos recurrentes.</h2><p className="mt-4 max-w-xl text-sm leading-relaxed text-[#61758a]">Acercá Urbi a inmobiliarias que necesitan su página web y participá del programa de comisiones por suscripciones cobradas.{maxCommission>0?` Escalas de hasta ${maxCommission}% según las condiciones del programa.`:" Consultá las condiciones vigentes."}{resellerSettings.activationBonusAmount>0?` También hay un bono de activación sujeto a ${resellerSettings.activationBonusDays} días pagos.`:""}</p></div><Link href="/revendedores" className="urbi-btn urbi-btn-primary justify-center">Conocer el programa <ArrowRight className="size-4"/></Link></div></div></section>
  <section className="mx-auto max-w-7xl px-6 py-20"><div className="mb-8 text-center"><p className="urbi-eyebrow">Antes de empezar</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">Resolvamos tus dudas.</h2></div><UrbiFaqList items={faqs} columns={2}/><Link href="/preguntas-frecuentes" className="mt-6 block text-center text-sm font-semibold text-[#1e658c]">Ver todas las preguntas →</Link></section>
  <section id="contacto" className="scroll-mt-24 bg-[#133453] text-white"><div className="mx-auto grid max-w-7xl items-center gap-8 px-6 py-16 md:grid-cols-[1fr_auto]"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#51c2ec]">Tu próximo paso empieza acá</p><h2 className="mt-3 max-w-xl text-3xl font-semibold tracking-tight">Un CRM, tu sitio web y la IA trabajando juntos.</h2><p className="mt-4 text-sm text-[#bad0df]">Contanos cómo trabaja tu inmobiliaria y te ayudamos a elegir el plan indicado.</p></div><ContactCtaButton label="Quiero empezar ahora" className={`h-12 justify-center px-6! ${ctaPop}`}/></div></section>
  <UrbiPublicFooter/>
 </main>;
}
