import Link from "next/link";
import { ArrowRight, Building2, Check, Globe, ImageIcon, KeyRound, MessageSquare, Palette, Smartphone, Users } from "lucide-react";
import { YaaPublicFooter } from "./yaa-public-footer";
import { YaaPublicNav } from "./yaa-public-nav";
import { YaaFaqList } from "./yaa-faq-list";
import { YaaPlans, type PublicPlan } from "./yaa-plans";
import { ContactCtaButton } from "./contact-cta-button";
import { SetupServiceSection } from "./setup-service-section";
import { FAQ_CATEGORIES } from "@/lib/faq-content";

const features = [
 {icon:Palette,title:"Una web con tu marca",text:"Tu nombre, logo, portada y datos de contacto. Una página que representa a tu inmobiliaria, con un enlace propio para compartir."},
 {icon:Smartphone,title:"Diseño moderno, también en el celular",text:"Tu catálogo se adapta a computadoras, tablets y celulares para que cada propiedad se vea bien desde cualquier pantalla."},
 {icon:ImageIcon,title:"Tus propiedades, bien presentadas",text:"Mostrá fotos, características, precios y descripciones en fichas de venta y alquiler fáciles de recorrer."},
 {icon:Globe,title:"Un sitio fácil de explorar",text:"Un buscador por zona, operación y dormitorios ayuda a cada visitante a encontrar lo que está buscando."},
 {icon:MessageSquare,title:"Consultas desde cada propiedad",text:"Los interesados pueden dejarte sus datos y su consulta directamente desde la ficha, sin crear una cuenta."},
 {icon:Building2,title:"Vos actualizás tu página",text:"Cargá propiedades, agregá fotos y cambiá precios desde tu panel. Publicá y ocultá los avisos cuando lo necesites."},
];
export function YaaLanding({plans,resellerSettings,resellerTiers,setupService}:{plans:PublicPlan[];resellerSettings:{activationBonusAmount:number;activationBonusDays:number};resellerTiers:{minActiveStores:number;percent:number}[];setupService:{enabled:boolean;price:number;steps:string[]}}) {
 const maxCommission=Math.max(0,...resellerTiers.map(t=>t.percent));
 const faqs=FAQ_CATEGORIES.flatMap(c=>c.questions).filter((_,i)=>[0,1,2,3,4,12].includes(i));
 return <main className="urbia-marketing min-h-screen bg-[#f7fafc] text-[#133453]">
  <YaaPublicNav/>
  <section className="relative overflow-hidden border-b border-[#e2ecf2] bg-[radial-gradient(ellipse_at_top_right,#d8f2f9,transparent_55%)]">
   <div className="mx-auto grid max-w-7xl items-center gap-8 px-6 py-10 lg:grid-cols-[1fr_1.05fr] lg:gap-12 lg:py-14">
    <div><p className="inline-flex items-center gap-2 rounded-full border border-[#cce4ee] bg-white/80 px-3 py-1.5 text-[11px] font-semibold uppercase tracking-[.14em] text-[#1e658c]"><span className="size-1.5 rounded-full bg-[#12a7cd]"/>Tu página web por un plan mensual</p>
    <h1 className="mt-5 text-4xl font-semibold leading-[1.1] tracking-[-.045em] sm:text-5xl lg:text-[52px]">Tu inmobiliaria.<br/>Tu propia web.<br/><span className="text-[#208ab1]">Un plan mensual.</span></h1>
    <p className="mt-4 max-w-lg text-base leading-relaxed text-[#61758a]">Dale a tu inmobiliaria una página moderna, rápida y adaptada a celulares. Mostrá tus propiedades con tu marca y recibí consultas, sin ocuparte del desarrollo.</p>
    <div className="mt-6 flex flex-wrap gap-3"><Link href="/registro" className="yaa-btn yaa-btn-primary h-12 px-6!">Quiero mi página web <ArrowRight className="size-4"/></Link><Link href="/demo" className="inline-flex h-12 items-center gap-2 rounded-xl border border-[#cbdce7] bg-white px-6 text-sm font-semibold hover:bg-[#edf5f9]">Ver cómo se vería</Link></div>
    <div className="mt-6 flex flex-wrap gap-x-5 gap-y-2 text-xs text-[#61758a]">{["Tu marca","Diseño adaptable","Panel para actualizarla"].map(t=><span key={t} className="flex items-center gap-1.5"><Check className="size-3.5 text-[#208ab1]"/>{t}</span>)}</div></div>
    {/* Espacio reservado para la futura imagen de portada. */}
    <div id="vista-previa" aria-hidden="true" className="hidden aspect-[4/3] w-full max-h-[380px] scroll-mt-24 lg:block" />
   </div>
  </section>
  <section className="border-b border-[#e2ecf2] bg-white"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-6 px-6 py-7"><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#8294a3]">Tu inmobiliaria, abierta a nuevas oportunidades</p><div className="flex flex-wrap gap-7 text-sm font-medium">{[[Palette,"Tu identidad"],[Smartphone,"En cualquier pantalla"],[Building2,"Tus propiedades"],[MessageSquare,"Más formas de contactarte"]].map(([Icon,t])=>{const I=Icon as typeof Building2;return <span key={String(t)} className="flex items-center gap-2"><I className="size-4 text-[#208ab1]"/>{String(t)}</span>;})}</div></div></section>
  <section id="funcionalidades" className="mx-auto max-w-7xl scroll-mt-24 px-6 py-20 lg:py-24"><div className="grid gap-5 md:grid-cols-2 md:items-end"><div><p className="urbia-eyebrow">Tu página, lista para mostrar lo mejor de vos</p><h2 className="mt-3 max-w-lg text-3xl font-semibold leading-tight tracking-tight sm:text-4xl">Una buena primera impresión.<br/>En cada visita a tu web.</h2></div><p className="max-w-md text-base leading-relaxed text-[#61758a] md:ml-auto">Diseño cuidado, tecnología web actual y las herramientas que necesitás para presentar tus propiedades de forma profesional.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{features.map(({icon:Icon,title,text})=><article key={title} className="rounded-2xl border border-[#e0eaf1] bg-white p-7 transition hover:border-[#98c9dc] hover:shadow-sm"><div className="flex size-11 items-center justify-center rounded-xl bg-[#eaf5fa]"><Icon className="size-5 text-[#208ab1]"/></div><h3 className="mt-6 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-[#61758a]">{text}</p></article>)}</div></section>
  <section id="como-funciona" className="bg-[#133453] text-white"><div className="mx-auto grid max-w-7xl gap-12 px-6 py-20 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#6cd0e7]">Así de simple</p><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">De tu inmobiliaria a tu propia página web.</h2><p className="mt-5 text-base leading-relaxed text-[#bad0df]">Elegí un plan, dale tu identidad al sitio y empezá a mostrar tus propiedades. UrbIA se ocupa de la plataforma; vos mantenés tu página al día.</p><Link href="/registro" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-[#78dbed]">Elegir mi plan <ArrowRight className="size-4"/></Link></div><div className="space-y-0">{[["01","Elegí tu plan mensual","Consultá los precios y las condiciones, y creá tu cuenta."],["02","Dale tu identidad","Sumá el logo, la portada y los datos de tu inmobiliaria."],["03","Publicá tus propiedades","Agregá fotos, precios y características desde tu panel."],["04","Compartí tu nueva web","Poné el enlace en tus redes y recibí consultas sobre tus avisos."]].map(([n,t,d])=><div key={n} className="flex gap-5 border-b border-white/10 py-5 first:pt-0 last:border-0"><span className="pt-1 font-mono text-xs text-[#6cd0e7]">{n}</span><div><h3 className="text-lg font-medium">{t}</h3><p className="mt-1 text-sm leading-relaxed text-[#bad0df]">{d}</p></div></div>)}</div></div></section>
  <section id="clientes" className="mx-auto max-w-7xl scroll-mt-24 px-6 py-20"><p className="urbia-eyebrow">Además de tu web</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">Un panel para mantenerla al día y acompañar tu trabajo.</h2><div className="mt-9 grid gap-8 md:grid-cols-3">{[[Building2,"Tus publicaciones","Administrá tu cartera, los precios y la disponibilidad de las ofertas desde el mismo lugar."],[Users,"Tus contactos y visitas","Reuní consultas, propietarios e interesados, y coordiná los próximos encuentros."],[KeyRound,"Tu gestión cotidiana","También contás con registro de operaciones, contratos y cobranzas manuales para organizarte."]].map(([Icon,t,d])=>{const I=Icon as typeof Building2;return <article key={String(t)} className="border-t border-[#cbdce7] pt-6"><I className="size-6 text-[#208ab1]"/><h3 className="mt-5 text-lg font-semibold">{String(t)}</h3><p className="mt-3 text-sm leading-relaxed text-[#61758a]">{String(d)}</p></article>;})}</div></section>
  <section id="precios" className="scroll-mt-20 border-y border-[#e2ecf2] bg-[#edf4f8] py-20"><div className="mx-auto max-w-6xl px-6"><div className="mx-auto mb-10 max-w-xl text-center"><p className="urbia-eyebrow">Tu web, por suscripción</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Elegí el plan para tu página.</h2><p className="mt-4 text-sm leading-relaxed text-[#61758a]">Un plan mensual para tener tu página inmobiliaria y el panel para actualizarla. Revisá las opciones y elegí la que acompaña a tu cartera.</p></div><YaaPlans plans={plans}/><p className="mt-6 text-center text-xs text-[#61758a]">Los precios corresponden a la suscripción de tu sitio y al acceso a la plataforma. El dominio propio está disponible en los planes que lo indican.</p></div></section>
  {setupService.enabled&&<SetupServiceSection price={setupService.price} steps={setupService.steps}/>}
  <section id="socios" className="mx-auto max-w-7xl scroll-mt-24 px-6 py-20"><div className="grid gap-8 rounded-3xl border border-[#d6e7ef] bg-white p-8 sm:p-12 md:grid-cols-[1fr_auto] md:items-center"><div><p className="urbia-eyebrow">Revendedores · Socios comerciales</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">Recomendá páginas inmobiliarias. Generá ingresos recurrentes.</h2><p className="mt-4 max-w-xl text-sm leading-relaxed text-[#61758a]">Acercá UrbIA a inmobiliarias que necesitan su página web y participá del programa de comisiones por suscripciones cobradas.{maxCommission>0?` Escalas de hasta ${maxCommission}% según las condiciones del programa.`:" Consultá las condiciones vigentes."}{resellerSettings.activationBonusAmount>0?` También hay un bono de activación sujeto a ${resellerSettings.activationBonusDays} días pagos.`:""}</p></div><Link href="/revendedores" className="yaa-btn yaa-btn-primary justify-center">Conocer el programa <ArrowRight className="size-4"/></Link></div></section>
  <section className="mx-auto max-w-3xl px-6 pb-20"><div className="mb-8 text-center"><p className="urbia-eyebrow">Antes de empezar</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">Resolvamos tus dudas.</h2></div><YaaFaqList items={faqs}/><Link href="/preguntas-frecuentes" className="mt-6 block text-center text-sm font-semibold text-[#1e658c]">Ver todas las preguntas →</Link></section>
  <section id="contacto" className="scroll-mt-24 bg-[#e5f3f8]"><div className="mx-auto grid max-w-7xl items-center gap-8 px-6 py-16 md:grid-cols-[1fr_auto]"><div><p className="urbia-eyebrow">Tu próxima página web empieza acá</p><h2 className="mt-3 max-w-xl text-3xl font-semibold tracking-tight">Hagamos que tu inmobiliaria se vea como merece.</h2><p className="mt-4 text-sm text-[#61758a]">Contanos sobre tu inmobiliaria y te ayudamos a elegir tu página y tu plan.</p></div><ContactCtaButton label="Contactar al equipo" className="yaa-btn yaa-btn-primary h-12 justify-center px-6!"/></div></section>
  <YaaPublicFooter/>
 </main>;
}
